use_frameworks!

platform :ios, '9.0'

target 'CMTAutoBind_Example' do
  pod 'CMTAutoBind', :path => '../'
#  pod 'CMTAutoBind', :git => "https://github.com/iJianbao/CMTAutoBind.git"

  target 'CMTAutoBind_Tests' do
    inherit! :search_paths

    
  end
end
